### ISSUE TITLE
Add a share button

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#1]
1. A simple share button to share the url with friends
2. A share button to send your itinerary to another friends device

**Comment by Pachena** [comment]
Both seem like good ideas to me... but I'm not the programmer!!!

**Comment by brettmarl** [comment]
simple link-share should be easy.

itinerary-share i think needs to wait on multiple-itinerary profiles, as if you clicked the link it would stomp over your settings. presumable you'd want to import the suggestion as a new profile and preserve whatever you had setup (if you had one).

**Comment by brettmarl** [comment]
did simple share button, still need share-trip.

**Comment by brettmarl** [comment]
closing - as dupe of #72
