### ISSUE TITLE
next-year tide tables

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#11]
One person asked when they can plan their 2024 trip (i assume to be ready to pick the best dates for owen pt?). 2024 tide data is available, but the dataset is too large iMHO to include multiple years of data for every hiker. add an optional setting to download an extra year of tide-data?

**Comment by Pachena** [comment]
Where is the 2024 tide data? The Canadian Hydrographic Service usually only releases it in December for the following year. I could work on my planning calendar sooner if I had access to it. Tide apps or websites that do not source CHS Tofino data can not be considered accurate.

**Comment by brettmarl** [comment]
2024 july is up here already?

https://www.tides.gc.ca/en/stations/08615/2024-07-27?tz=PDT&unit=m

**Comment by brettmarl** [comment]
even september is up: https://www.tides.gc.ca/en/stations/08615/2024-09-15?tz=PDT&unit=m

**Comment by Pachena** [comment]
awesome thank you! The last couple of years it was December so I had to
rush to get it out for Christmas.

I can do my planning calendar *now *for 2024.

**Comment by brettmarl** [comment]
done
