### ISSUE TITLE
Hiker-suggested trail conditions

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#13]
Allow hikers to upload trail conditions reports.

**Comment by Pachena** [comment]
As previously discussed - allowing hikers open access could lead to a lot of inaccurate or subjective comments. I like your proposal of a filtering email which can then be screened for useful information to add to the trail conditions.

**Comment by Pachena** [comment]
Is this still a consideration or closing it due to the many issues it creates?

**Comment by brettmarl** [comment]
I think we can leave it open for a while... the best case I can think for it at this point is to just have hikers be able to 'report' an issue - with text/photo maybe - which goes into an email / queue somewhere for us to look at and consider if the issue if worthy of adding to the report. I don't ever see this feature as a direct-to-app feedback without manual intervention/approval...

**Comment by brettmarl** [comment]
thinking more about this over the weekend... i good first step here might be to allow people to report on water-sources. they could click on a source and pick from a few options like [lots of water, some water, running low, no water - dried up].

**Comment by brettmarl** [comment]
calling this done
