### ISSUE TITLE
summary page needs more love...

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#15]
layout is super hard on this page on small devices, so it's pretty messy. could do things like separate distances-table from trip table or tide-impacts.

**Comment by Pachena** [comment]
I will provide more feedback and ideas this week.

What happened to #14?!

**Comment by brettmarl** [comment]
#14 got closed, as not needed?

**Comment by Pachena** [comment]
I found 14 - didnt know there was a closed section. Newbie here, but I'm
catching on :-)

**Comment by brettmarl** [comment]
better than it was...
