### ISSUE TITLE
permit market place

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#16]
WCT app could be a 'broker' for folks wanting to resell their permits. people could list/advertise and WCT app can manage the transaction ensuring that one side pays the other other side correctly transfers. WCT app could take a small cut for the service (plus CC fees)

**Comment by Pachena** [comment]
Is this sort of thing possible from a programming perspective? It sounds like a MASSIVE upgrade as it requires CC security, user input etc. I think its a cool idea as long as the ads are removed when a) the transaction is complete or b) the start date has passed. A simpler form might be to have someone list their pass, start date, and provide and email contact. This removes the app from the transactional process and potential messy situations of someone paying but not getting the passes transferred. We can not control the pass transfer - it has to be done through Parks Canada as the names on the reservation need to be changed, Thoughts?

**Comment by brettmarl** [comment]
closing as a 'never really gonna do this' feature ;)

**Comment by Pachena** [comment]
I like your assessment of this not-gonna-ever-be feature!!
