### ISSUE TITLE
Add motorcycle icon / POI

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#22]
(need text from Lance)

**Comment by Pachena** [comment]
create icon. text "motorcycle" until I complete the text revisions.

**Comment by brettmarl** [comment]
done
![image](https://github.com/brettmarl/wct-status/assets/1099372/9c851f03-e2a4-48a9-8599-775af0efc349)

**Comment by brettmarl** [comment]
done
![image](https://github.com/brettmarl/wct-status/assets/1099372/d334625c-66ea-49c7-92ad-335e5f0eb97e)
