### ISSUE TITLE
hard/easy sections

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#23]
add better descriptions to hard sections (eg. walbran->camper, thrasher boulders etc) and maybe include some possible timing in text for now?

**Comment by Pachena** [comment]
Timing is subjective. Mike Blake and a bunch of hardcore May 1st hikers went Gordon to Camper in a day. A Parks warden went Gordon to Cullite. A tiny little asian girl went Gordon to Walbran!!!! All had packs weighing more than yours. 

I like what you have done for difficulty of sections on the cards. VERY NICE. There needs to be a little more added to separate the beach and forest sections. Difficulty: Easy (beach) Moderate (forest) for example

**Comment by brettmarl** [comment]
closing for now - think it's good enough, can revisit timing another day...
