### ISSUE TITLE
Hi-Res Maps & Layer-Refactor

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#24]
re-render map to be higher-resolution for wider displays/fullscreen. the new medium layout on desktop looks pixelated. rework map base icons to be a item-layer vs. image (ditto with ladders and ships), to allow for faster map changes.

**Comment by Pachena** [comment]
All of the above. . . and use the 2019 map instead so points like Dare are captured correctly?

**Comment by Pachena** [comment]
As a follow up to this - is there any value in making slight adjustments to the Parks map to show the beach access locations and trail position more accurately in some areas? eg: Tsusiat to Nitinaht

**Comment by brettmarl** [comment]
Sure - why not. I dialed back the max desktop width a bit so they look less
gainy on desktop as a temporary work around. but higher res and newer
generations maps with orientation tweaks, whatever we want to do... it's
going to be a PAINFUL project, as i'll have to redo all the icon positions
and ladders and shipwrecks and all the geo-reference points. but lets get a
list going of improvements ideas I can do it all at the same time.

**Comment by brettmarl** [comment]
done
