### ISSUE TITLE
GPS - finalize UI

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#26]
Gps button conflicts with labels and shipwrecks Consider merging all 3 buttons (full-screen, layers, GPS) into to a single action button in lower right. Or explore GPS button out of the map on the navbar?

**Comment by Pachena** [comment]
Interesting idea. This is something that would de-clutter the map. Already there are several options on the one button so why not add more. Maybe the button icon itself can glow / flash when the GPS is active to alert users to the function and battery drain potential.

**Comment by brettmarl** [comment]
leaving alone for now...
