### ISSUE TITLE
Dark tides

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#27]
As september / shorter days approach, dark-tides become more interesting to people with limited hours. Making this default adds too much clutter for the majority case, but can we make user aware there are dark-windows available and/or direct them to enable the setting more easily.

**Comment by Pachena** [comment]
Agree - the option for dark tides (and probably other app options) need to be made more available. Maybe in the "settings" menu :-)

**Comment by brettmarl** [comment]
fixed
