### ISSUE TITLE
Home page - rethink...

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#28]
Most frustrating part of using the app for me on the trail, was scrolling through segments I no-longer cared about as I had hiked them on the home page. 

Explore some ideas to break up  home page into 'days' so i don't have to scroll down previous days stuff. maybe auto-select or button to goto current day, so I have less segments to look at in the list.

**Comment by Pachena** [comment]
This is not a bad idea. We often ignore the user experience as we are constantly scrolling back and forth through the cards making adjustments. If you are on day 7 the last thing you want is to be scrolling through the past 6 days (the entire trail) to get to your current card.

Can you tie in the system date to the planned date on the card and ignore previous (but have an option to show them)???

**Comment by brettmarl** [comment]
added a day-filter bar on the homepage, and a triangle to hint towards 'today'. also shows relative dates (today, yesterday, tomorrow)

![home-days](https://github.com/brettmarl/wct-status/assets/1099372/4d7664e3-5622-4e15-bde8-4bb87c208716)

**Comment by Pachena** [comment]
Can I say that the new day filter bar looks cool - but way to big! Maybe
half the height and shade the current day instead of the arrow? This is
kind of standard in date related things - the current day is shaded.
