### ISSUE TITLE
suggestion: '5km,  feels like 8km'

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#29]
interesting hiker suggestion: on harder sections show rating in a wind-chill like format. eg. 42f feels like 32f (with wind chill). so gordon->thrasher might be 5k (Feels like 8k).

**Comment by Pachena** [comment]
Many of the hiker comments / suggestions are very subjective. You might find that 6km (its 5km to the junction +1 down the hill to the beach) to be fairly easy, but the hiker who took 10 hours might strongly disagree. To them the 6km feels like 75km but to you it might feel like 6km.

**Comment by brettmarl** [comment]
closing as too subjective to be actionable and current difficulty rating good enough for now
