### ISSUE TITLE
Multiple itineraries 

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#3]
For YOYO hikers, or even hikers considering multiple options - have the ability to save a itinerary to named-list.

**Comment by Pachena** [comment]
This I like. The Nitinaht to Tsusiat to Gordon River hike is something that the app currently does not cover well and is fairly common for hikers who can not get a N/S reservation. This year already we have had 3 groups come through Pachena Point who were doing a Nitinaht-Pachena-Gordon River hike.

**Comment by brettmarl** [comment]
fixed
