### ISSUE TITLE
#30 - Rotate Pachena Bay to Malsit and Malsit to Michigan

### ISSUE THREAD

**Issue by Pachena** [brettmarl/wct-status#30]
Is it possible to rotate these two map sections a bit to make them a little bit more representative of the actual map direction? The Pachena Bay to Malsit trail ends heading in an upward direction (top right)! Maybe rotate a bit to be corner to corner instead of left to right. 

Something to consider if new map images are produced from more current maps and/or higher resolution

**Comment by brettmarl** [comment]
If I rotate Pac>Malsit then I loose a spot to put shipwrech Soquel. 

Mal->Michigan isn't rotated from the original (I believe), not sure what you had in mind for that one. 

![image](https://github.com/brettmarl/wct-status/assets/1099372/4b30268a-1a00-45ce-b1b3-adb27e835cc1)

**Comment by brettmarl** [comment]
vs current:

![image](https://github.com/brettmarl/wct-status/assets/1099372/ed80d401-afc5-4a50-8be5-5171d7474edd)

**Comment by Pachena** [comment]
I like the first rotation. The extreme one loses the pachena trailhead area. Soquel shipwreck can be added at the bottom edge of the map. It was on seabird rocks... actually not visible on any of the maps!

I like the additional dots on the beach but maybe a diagonal line instead of the dramatic L shape?!

**Comment by Pachena** [comment]
Malsit to Michigan was thinking of rotation to move slight closer to the parks map aspect. Move Malsit up, Michigan down. Rotate around Pachena LH area as the central hub for rotation?

**Comment by brettmarl** [comment]
fixed new maps
