### ISSUE TITLE
Add Parks emergency evac number and procedure?

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#31]

**Comment by Pachena** [comment]
Love this idea. Maybe have it in the hamburger menu. What is the capacity of the App for photos? We could get a good photo or scan of the Parks Evacuation card and put that in there?

**Comment by brettmarl** [comment]
Easy to add photos. I left my evac card at the orientation office. Too
heavy ;)

**Comment by brettmarl** [comment]
closing this as will be covered by #32
