### ISSUE TITLE
Add info pages / section

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#32]
Stuffing things in the 'burger menu' is going to get unscalable very quickly. Thinking there is a more 'guidebook' portion of the app that is accessed via the burger menu and has its own navigation hierarchy to that it can scale infinitely. 

Some ideas for topics/pages might include:

Entering at Pachena]
Entering at Nitinat]
Entering at Gordon
Evacuation
Camps
History
Getting Here & Transport
Useful numbers
Ferry times, fees and crossing info. (esp. complexity of paying nitinat ferry @ crabshack vs. to Parks)

Wanted to open an issue to keep tracking ideas along these lines...

**Comment by Pachena** [comment]
- Transportation / Accommodation / Places to Eat - Port Renfrew, Nitinaht, Bamfield
- History - no special section required as bits will be included in text descriptions along the trail. Virtually no history available south of Cheewhat as there was nothing there and nothing happening except at Carmanah Lighthouse.!
-

**Comment by brettmarl** [comment]
don!
