### ISSUE TITLE
Tide Gap Confusing

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#33]
When dark tides are on, sometimes the gap be be confusing. For example:

![image](https://github.com/brettmarl/wct-status/assets/1099372/ae5d977c-3161-4839-8fc7-ccdf4e34e2d8)

What's going on here is that sunrise is 7:06am. To save the download size for the whole year, we only download tide data on 15-minute increments. 

So when calculating times that are dark we get 6:15-7:00am (as the next passable 7:15 is daylight), and there appears to be a weird 15m gap between the dark-window and the day-window. 

Not quite sure how to fix this, for these edge cases, we could assume tide data and adjust the windows around the sunrise time:
6:15am-7:05am (DARK) and 7:06am - 12:45pm  

but it's a little risky to assume data, and inconsistent to have a tide-window that is not in 15m increments. 

Not sure it needs to be fixed, but wanted to log it and think about it a bit...

**Comment by Pachena** [comment]
Considering that the "official" tide tables are giving data hourly I think if you nudge the times based on sunrise that the tide changes within that 15 minutes will be minimal. If someone shows up to a tidal dependant location LATE, within 15 minutes of it being impassable, then they can probably wade through ankle deep water at most. If they show up 15 minutes EARLY and it's not passable yet, they will probably be happy to have a short break anyway. It can easily be explained by the fact that tides are technically not "tables" but "predictions" and weather (wind) can also affect tides too.

**Comment by Pachena** [comment]
Another idea - Looking at the 6:15 am - 12:45 pm passable section would it be possible to have a single oval section that shows 6:15 am - 12:45 pm and have it shaded with a gradient from dark tide to light tide and show the sunrise time in the middle?
6:15 am - 7:06 am - 12:45 pm for example?

**Comment by brettmarl** [comment]
> 

gradient-window is tricky, as sometimes the span can be hours - eg. 2am - 8:15am with sunrise a 8:07. not sure that would be useful to have in a single window, it seems at most a little bit before sunrise is good, but showing a window with hours of darkness isn't that useful.

**Comment by brettmarl** [comment]
fixed with new 1-minute intervals
