### ISSUE TITLE
North and South of Tsusiat Pt tide cut offs

### ISSUE THREAD

**Issue by Pachena** [brettmarl/wct-status#34]
Hikers reported this morning being unable to pass headlands both north and south of Tsusiat Pt due to tides. Reviewing tide data for that day. 

Possibly extend the green beach section? Possibly add more description?

**Comment by Pachena** [comment]
As mentioned in the email, a note in the description that "at extreme high tides the points immediately north and south of tsusiat point may be impassable requiring hikers to use the forest route from KM27.5 BA to Tsusiat Falls." should be enough to cover this without messing up the map. It's such a rare occurrence.

**Comment by brettmarl** [comment]
Do we know what the king-tide value is that causes that? I can add logic to
show this if daily highs are > it?

**Comment by Pachena** [comment]
tide was 3.5m at the time the hikers could not get past both sections. I just think a note in the description covers the day or two each summer that this becomes an issue

**Comment by brettmarl** [comment]
fixed
