### ISSUE TITLE
Distance chart 

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#36]
During our trip when changing plans we often had to do math to calculate how far we planned to go. Nigel asked a few times for my distance matrix (in spreadsheet) - so maybe put this in the app or a dynamic version of it based off gps and/or selected locations.

**Comment by Pachena** [comment]
A list of campsites / locations and their KM markers is easy. 
Do you want just a list people can look at or a dynamic one showing the distance to all of them from current location?

**Comment by brettmarl** [comment]
![IMG_6598](https://github.com/brettmarl/wct-status/assets/1099372/18ef83fd-5b2a-4792-8f0e-83fc70579ff1)

this is the chart Nigel was talking about but it could be coded with a from/to drop-down

**Comment by brettmarl** [comment]
i think this is covered now by the new trip setup page
