### ISSUE TITLE
Add Boat Icon to Nitinaht and Gordon River

### ISSUE THREAD

**Issue by Pachena** [brettmarl/wct-status#39]
List ferry times for Gordon River and Nitinaht (crossing and up/down the lake) 
Add cost for up/down lake (self evac) and for charter at non-scheduled times

**Comment by Pachena** [comment]
Icon can also allow for some info about First Nations and Butch and Carl

**Comment by brettmarl** [comment]
Done for now - although i like the idea of working more info about FN ferry operators into the cards, so hesitant to close this out - good to keep as a reminder?

**Comment by Pachena** [comment]
Suggest closing this. I think the way the ferry card is set up is not great for adding lots of info. I will include whatever First Nations info I can into the Nitinaht Narrows and Gordon River and Pachena Bay place names so we can leave the ferry card to just the ferries.

**Comment by brettmarl** [comment]
closing
