### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#4]
This has been requested by a few people wanting a print-out of the 'summary page' showing their distances and tide-windows. I guess as a backup incase phone dies?

**Comment by Pachena** [comment]
Not a bad idea as a dropped phone into a mud puddle or tide pool and its game over. I honestly have not put much effort into reviewing the summary page as I have been focused on the details of the individual cards. I will start to critique this more and then you can maybe add a print button where it can be printed to PDF or something. Don't forget the branding name and logo when it get printed as it will likely be shared at campsites with other hikers!

**Comment by brettmarl** [comment]
started this for tides #98 covering open-issues
