### ISSUE TITLE
Reconcile icon popup with full card 

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#40]
Some places (crab shack) have info in a popup and info in their own card. The card is a richer experience but maybe less discoverable (scroll). In crabshacks case the card is kind of the “camp” card. With ferry times - a card would be more richer layout. Think about how to consolidate when doing ferry times.

**Comment by Pachena** [comment]
I think a ferry icon with ferry times and a crab icon with crabshack info is the best approach. Separate the ferry times and info from the crabshack accommodation and food info.

**Comment by brettmarl** [comment]
not perfect - but good enough for now...
