### ISSUE TITLE
Ferry-Times Card

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#7]
Add card to Nitinat and Gordon showing ferry times / details.

**Comment by Pachena** [comment]
Not required. Times can be noted in the description - as you have already done for Gordon River.

**Comment by brettmarl** [comment]
it's in the description - but could be lifted out into its own thing to keep the description cleaner. a separate card could be accessed via the burger menu too. thinking it could be formatted in a more useful way too, as people often seem to wonder 'can i make orientation and take the ferry right after', or 'can i do orientation a day before and take the first ferry' etc. it's own card would allow more space to elaborate on options.

**Comment by Pachena** [comment]
I might revise my statement here now that we have excellent touch pop-up icons. Adding icons for the two ferries would allow the times (and a little bit of info) to be on a pop up window. I like this idea!

**Comment by brettmarl** [comment]
closing as dupe of https://github.com/brettmarl/wct-status/issues/39
