### ISSUE TITLE
 Cribs is at KM41.5 not 42

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#77]
Dare to Cribs - Cribs is at KM41.5 not 42 but the decimals might mess up your programming? Water sources for Cribs 41.5 and Coal 42 often flow together at Cribs 41.5

**Comment by brettmarl** [comment]
It would definitely hurt the layout, as the segment KM-marker are assumed max of 2-digits for start/ends. 

![image](https://github.com/brettmarl/wct-status/assets/1099372/ea0d3225-bfcb-4f3c-b7f6-05070633d0f0)


Hesitant to try and move Cribs itself, but could add a water source of "Cribs" at 41.5.  Skip Coal as it is the same thing once merged into Cribs? They look so far apart on the map! Oh - wait - on second thoughts, that's a bad idea, as if I move the water source to 41.5 then it will only show on dare_cribs and not cribs_carmanah, which is bad when going NOBO... tempted to let this be for now...

**Comment by Pachena** [comment]
agree. leave it alone. it was just a nit-picky observation that doesn't really affect anything.

**Comment by brettmarl** [comment]
closing
