### ISSUE TITLE
Map Edits - Carmanah Chaos

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#78]
Carmanah Point - can you work your magic to move the 44km below the trail and the ladder icon above it? The IH is nearly impossible to touch and if the 44 was closer to it instead of the ladder then it would be touchable as the 44 is not touchable. See attached.

![carmanah point edits](https://github.com/brettmarl/wct-status/assets/1099372/a23c97cf-4e73-4cc3-a449-cb984428521a)

**Comment by brettmarl** [comment]
@Pachena  - this is actually quite a lot better now that the touch-target for ladders is adjusted. give it a try and see what you think...

**Comment by Pachena** [comment]
ok - it works well. close it.
