### ISSUE TITLE
Weather support

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#8]
I suspect most people are using the weather networks "WCT" weather forcast:

https://www.theweathernetwork.com/ca/14-day-weather-trend/british-columbia/pacific-rim-national-park-west-coast-trail

I also suspect the trail is more of a microclimate and conditions might be different north/south. 

Idea would be to be able to pull geo-pinpointed data from a wether service-api and use the planned itinerary to show more accurate prediction for the part of the trail you will be travelling on the date you will be travelling. 

could also try and factor in some marine weather to the tide-preductions, eg. if trying owen pt on a narrow window - could we warn when wind-driven waves or marine-swell is more likely due to sea state. apps like WIndy and Predict Wind are cool - but have a steep learning curve on how to interpret the data.

**Comment by Pachena** [comment]
This is bold and very cool sounding but is the level of detail required? Maybe something to play with in the future, At times there is significant difference between the south and north ends (Clo-oose or Dare Pt being the approximate dividing line) for weather but I think most hikers are more black and white on their weather requirements... rain / no rain. Note - Windy seems to be very poor along the coast. Often in the middle of a 30-40kt storm I put the pin on Pachena and Windy says it's 18kts. Their fog predictions are not bad though!
