### ISSUE TITLE
Pull more FN names from 2007 Parks Map

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#86]

**Comment by Pachena** [comment]
I like this. It might mean getting some content adjustments though but it can be worked - eg 150 yard creek is mentioned in the text as a cut point for the forest route on Camper to Owen

**Comment by brettmarl** [comment]
I pulled all the other names into the backend, you can see a lot more PFN here now:

https://www.westcoasttrail.app/a/text/FirstNationText

but still need to figure out how to show them in the App...

**Comment by brettmarl** [comment]
closed as i have all the data and #91  covers finding homes for them.
