### ISSUE TITLE
Todo: find homes for more of the Ditidaht Audio clips on the map

### ISSUE THREAD

**Issue by brettmarl** [brettmarl/wct-status#91]

**Comment by brettmarl** [comment]
Notes from Lance:

In the south Bonilla is the line. Parks map has PFN but a line is usually named by the people who are on both sides. In this case I would use PFN 1 and DFN 2. In the north it's far more complicated. DFN claim to Pachena Point and HFN claim to Tsusiat River. In this case I would set it up based on the guardians territory and give it to HFN 1st and DFN 2nd. It's a diplomatic solution that is simply following the current territorial guardians coverage.

 Non map names are easy (in my opinion). Pachena Pt and the Beach should go with the icon for Pachena Pt Lighthouse. Whyac can do with the Nitinaht Narrows name as it's mentioned in my write up. Coal creek - with Cribs Creek. I can adjust the write up to include a brief comment about the coal mining there. etc etc.

Cullite in the south can get confusing so be careful. Cullite cove was called Kowshet Cove for a long time. The name Cullite was applied to a large PFN village at Kulaht Creek. The parks map has it named. Pachena and Cullite are very confusing as they refer to places that are different from where the current names are used. Pachena for example was supposed to be for Port Renfrew because thats where the Pacheedaht live but it was mis-labeled as the two bays look similar.

**Comment by Pachena** [comment]
What audio clips are still needing homes? I can offer suggestions. . .

**Comment by brettmarl** [comment]
Full list is here - also lots of non audio names that aren’t being used.
Especially PFN.

https://www.westcoasttrail.app/a/text/FirstNationText

**Comment by Pachena** [comment]
Suggest adding the DFN names to points north and if/when we get HFN names we can then add them in as well. 
Pachena Point and Beach can be added to the lighthouse. The rest are obvious. Coal creek should be added to the Cribs Creek card.

**Comment by brettmarl** [comment]
Don't think it's quite so simple to use Pachena ones on the lighthouse... right now the translate icon shows next to the name, so it would be weird to have a translation for "Pachena Point Lightstation" - and each popup-dialog hosts one translation name with multiple FN variants. 

Think need to find a way to show these and other things like 150-yard, Trisle Ck also. Thinking maybe it needs it's own layer on the map.

**Comment by brettmarl** [comment]
fixed for now in a first nations section
